version: '3.8'

services:

  web:
    build: .
    restart: always
    volumes:
      - .:/usr/src/web/
      - static_data:/usr/src/web/static/
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6-alpine
    restart: always
    container_name: nginx
    volumes:
      - static_data:/usr/src/web/static
      - media_data:/usr/src/web/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
  media_data: