# Generated by Django 3.0.5 on 2020-11-19 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201119_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(db_index=True, null=True, validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
