# Generated by Django 3.0.5 on 2020-11-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20201119_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'verbose_name': 'Title', 'verbose_name_plural': 'Titles'},
        ),
    ]
