# Generated by Django 3.0.5 on 2020-11-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20201119_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='titles'),
        ),
    ]
