# Generated by Django 3.0.5 on 2021-02-07 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20201123_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(db_index=True, null=True, validators=[django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
